spring:
  datasource:
    url: jdbc:mysql://localhost:3306/RD_Edu_LMS?createDatabaseIfNotExist=true
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB